const mongoose = require("mongoose");
const blogPostSchema = new mongoose.Schema({
  authorEmail: { type: String },
  authorName: { type: String },
  authorMail: { type: String },
  commentCount: { type: Number },
  commentStatus: { type: String },
  guid: { type: String },
  menuOrder: { type: Number },
  pingStatus: { type: String },
  pinged: { type: String },
  postAuthor: { type: String },
  postContent: { type: String },
  postContentFiltered: { type: String },
  postExcerpt: { type: String },
  postMimeType: { type: String },
  postName: { type: String },
  postParent: { type: Number },
  postPassword: { type: String },
  postStatus: { type: String },
  postStatusSyndication: { type: String },
  postTitle: { type: String },
  postType: { type: String },
  schedulePostDate: { type: Date },
  siteId: { type: String },
  toPing: { type: String },
  postDate: { type: Date },
  postDataGmt: { type: Date },
  postModified: { type: Date },
  postModifiedGmt: { type: Date },
  websiteUrl: { type: String },
  postMeta: { type: String },
});
const BlogPost = mongoose.model("BlogPost", blogPostSchema);
module.export = BlogPost;
